# variables:
#   GIT_STRATEGY: clone
#   JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

# stages:
#  - test

# test:
#  stage: test
#  image:
#    name: debian:bookworm
#    pull_policy: always # available: always, if-not-present, never
#  script:
#   - apt update
#   - apt install -y wget apt-transport-https gnupg
#   - mkdir -p /etc/apt/keyrings
#   - wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
#   - echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
#   - apt update
#   - apt install -y temurin-17-jdk ant ivy git curl
#   - git submodule init
#   - git submodule update
#   - ant fetch-metrics-lib
#   - ant -lib /usr/share/java resolve
#   - ant test
#   - ant checks
