variables:
  GIT_STRATEGY: clone
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

stages:
 - test

test:
 stage: test
 image:
   name: debian:bookworm
   pull_policy: always # available: always, if-not-present, never
 script:
  - apt update
  - apt install -y wget apt-transport-https gnupg
  - wget -qO - https://packages.adoptium.net/artifactory/api/security/keypair/default-gpg-key/public | apt-key add -
  - echo "deb https://packages.adoptium.net/artifactory/deb/ bookworm main" | tee /etc/apt/sources.list.d/adoptopenjdk.list
  - apt update
  - apt install -y adoptopenjdk-11-hotspot ant ivy git curl
  - git submodule init
  - git submodule update
  - ant fetch-metrics-lib
  - ant -lib /usr/share/java resolve
  - ant test
  - ant checks
