name: 'Deploy new version'
inputs:
  environment:
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy new version
      env:
        NOMAD_CACERT: operations/admin-ui-ca.crt
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN_ONIONOO_DEPLOY }}
        NOMAD_ADDR: ${{ secrets.NOMAD_DEPLOY_ADDR }}
      run: |
        curl -L https://releases.hashicorp.com/nomad/1.6.3/nomad_1.6.3_linux_amd64.zip -o nomad.zip
        unzip nomad.zip
        ./nomad job run operations/deploy-${{ inputs.environment }}.hcl
