version: '2.2'
services:
  onionoo-jar:
    image: onionoo
    restart: always
    environment:
      COLLECTOR_HOST: host.docker.internal:9000
      COLLECTOR_PROTOCOL: "http://"
      UPDATER_PERIOD: 2
      UPDATER_OFFSET: 0
      BASE_DIR: "/srv/onionoo"
      LOGBASE: "data/logs"
      TYPE: jar
    volumes:
      - ./onionoo-data/:/srv/onionoo/data
  onionoo-war:
    image: onionoo
    restart: always
    environment:
      BASE_DIR: "/srv/onionoo"
      LOGBASE: "data/logs"
      TYPE: war
    ports:
      - "8080:8080"
    volumes:
      - ./onionoo-data/:/srv/onionoo/data
  onionoo-cron:
    image: onionoo-cron
    restart: always
    environment:
      ONIONOO_HOST: "http://host.docker.internal:8080"
      INTERVAL_MINUTES: 2
      METRICS_FILE_PATH: "/srv/onionoo/data/out/network/metrics"
      CRON_EXPRESSION: "*/2 * * * *"
    volumes:
      - ./onionoo-data/:/srv/onionoo/data