version: '2.2'
services:
  onionoo-jar:
    image: onionoo
    restart: always
    environment:
      COLLECTOR_HOST: host.docker.internal:9000
      COLLECTOR_PROTOCOL: "http://"
      UPDATER_PERIOD: 5
      UPDATER_OFFSET: 2
      BASE_DIR: "/srv/onionoo"
      LOGBASE: "data/logs"
      TYPE: jar
    volumes:
      - ./onionoo-data/:/srv/onionoo/data
  onionoo-war:
    image: onionoo
    restart: always
    environment:
      BASE_DIR: "/srv/onionoo"
      LOGBASE: "data/logs"
      TYPE: war
    ports:
      - "8080:8080"
    volumes:
      - ./onionoo-data/:/srv/onionoo/data
