name: Build and Push Docker Image
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-tag:
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push Docker image of service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ inputs.docker-username }}/onionoo:${{ github.sha }},${{ inputs.docker-username }}/onionoo:${{ inputs.docker-tag }}

    - name: Build and push Docker image of cron task
      uses: docker/build-push-action@v2
      with:
        context: ./metrics
        file: ./metrics/Dockerfile
        push: true
        tags: ${{ inputs.docker-username }}/onionoo-cron:${{ github.sha }},${{ inputs.docker-username }}/onionoo-cron:${{ inputs.docker-tag }}
