name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-tag: latest-dev
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: dev
