name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image of service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/onionoo:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/onionoo:latest

      - name: Build and push Docker image of cron task
        uses: docker/build-push-action@v2
        with:
          context: ./metrics
          file: ./metrics/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/onionoo-cron:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/onionoo-cron:latest

      - name: Deploy new version
        env:
          NOMAD_CACERT: operations/admin-ui-ca.crt
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN_ONIONOO_DEPLOY }}
          NOMAD_ADDR: ${{ secrets.NOMAD_DEPLOY_ADDR }}
        run: |
          curl -L https://releases.hashicorp.com/nomad/1.6.3/nomad_1.6.3_linux_amd64.zip -o nomad.zip
          unzip nomad.zip
          ./nomad job run operations/deploy-dev.hcl
