name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: live
          nomad-cacert: operations/admin-ui-ca.crt
          nomad-token: ${{ secrets.NOMAD_TOKEN_ONIONOO_DEPLOY }}
          nomad-addr: ${{ secrets.NOMAD_DEPLOY_ADDR }}
